# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("lib", __dir__)
require "baking_rack/version"

Gem::Specification.new do |gem|
  gem.name     = "baking_rack"
  gem.license  = "MIT"
  gem.version  = BakingRack::VERSION

  gem.author   = "Dan Cunning"
  gem.email    = "dan@rapidlybuilt.com"
  gem.homepage = "https://rapidlybuilt.com/gems/baking-rack"
  gem.summary  = "Bake and Push static webpages generated by a Rack application."
  gem.required_ruby_version = ">= 3.1"

  gem.description = gem.summary

  gem.files = Dir["**/*"].grep(%r{^(README|bin/|data/|ext/|lib/|spec/|test/)})

  gem.metadata = {
    "rubygems_mfa_required" => "true",
  }

  gem.add_dependency "zeitwerk", "~> 2"
end
